// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk5BMm1JzUbn3uuNY4Zdd11LLZZ3A2qEQ',
    appId: '1:985991997427:web:b33038152650c724c05486',
    messagingSenderId: '985991997427',
    projectId: 'achieve75-6f726',
    authDomain: 'achieve75-6f726.firebaseapp.com',
    storageBucket: 'achieve75-6f726.appspot.com',
    measurementId: 'G-DGS3PPEKWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3rwGJRF_HydP0jMuhYPPRATdyX6axD2o',
    appId: '1:985991997427:android:4f8a87863b1f0091c05486',
    messagingSenderId: '985991997427',
    projectId: 'achieve75-6f726',
    storageBucket: 'achieve75-6f726.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIGVihbEKbvZRMT8My7PCH8iAScqXsY6Q',
    appId: '1:985991997427:ios:7d6618039bd7689bc05486',
    messagingSenderId: '985991997427',
    projectId: 'achieve75-6f726',
    storageBucket: 'achieve75-6f726.appspot.com',
    iosBundleId: 'com.juhaszweb.achieve75',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIGVihbEKbvZRMT8My7PCH8iAScqXsY6Q',
    appId: '1:985991997427:ios:7d6618039bd7689bc05486',
    messagingSenderId: '985991997427',
    projectId: 'achieve75-6f726',
    storageBucket: 'achieve75-6f726.appspot.com',
    iosBundleId: 'com.juhaszweb.achieve75',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk5BMm1JzUbn3uuNY4Zdd11LLZZ3A2qEQ',
    appId: '1:985991997427:web:a46dd6cc8d90b763c05486',
    messagingSenderId: '985991997427',
    projectId: 'achieve75-6f726',
    authDomain: 'achieve75-6f726.firebaseapp.com',
    storageBucket: 'achieve75-6f726.appspot.com',
    measurementId: 'G-NJYFLZ26LZ',
  );
}
